import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const slots = JSON.parse(readFileSync(join(here, "..", "slots.json"), "utf8"));

const esc = (s) => String(s).replace(/'/g, "''");
const val = (v) => (v === null || v === undefined ? "NULL" : `'${esc(v)}'`);

const rows = slots
  .map(
    (s) =>
      `(${s.id}, '${s.table}', '${esc(s.block)}', '${esc(s.time)}', ${val(s.tag)}, '${s.color}', '${s.col}')`,
  )
  .join(",\n");

const sql = `-- GENERATED by scripts/gen-seed.mjs. Do not edit by hand.
insert into public.slots (id, table_name, block, time_label, tag, color, col_pos) values
${rows}
on conflict (id) do update set
  table_name = excluded.table_name,
  block = excluded.block,
  time_label = excluded.time_label,
  tag = excluded.tag,
  color = excluded.color,
  col_pos = excluded.col_pos;
`;

writeFileSync(join(here, "..", "supabase", "seed.sql"), sql);
console.log(`Wrote ${slots.length} slot rows to supabase/seed.sql`);
